pipeline {
    agent any // Run on any available agent

    stages {
        stage('Checkout Code') {
            steps {
                // Checkout the code from the repository
                checkout scm
            }
        }

        stage('Set Up Python') {
            steps {
                // Set up Python environment for Windows
                bat 'python -m venv venv'
                bat '.\\venv\\Scripts\\activate && pip install -r requirements.txt'
            }
        }

        stage('Run Tests') {
            steps {
                // Run pytest and generate HTML report
                bat '.\\venv\\Scripts\\activate && pytest -v -s --self-contained-html --html=reports\\Test_Execution_Report.html'
            }
        }
    }

    post {
        always {
            // Archive test reports
            archiveArtifacts artifacts: 'reports\\Test_Execution_Report.html', fingerprint: true
        }
    }
}
