pipeline {
    agent any // Run on any available agent

    stages {
        stage('Checkout Code') {
            steps {
                // Checkout the code from the repository
                checkout scm
            }
        }

        stage('Set Up Python') {
            steps {
                // Set up Python environment
                sh 'python3 -m venv venv'
                sh '. venv/bin/activate && pip install -r requirements.txt'
            }
        }

        stage('Run Tests') {
            steps {
                // Run pytest and generate HTML report
                sh '. venv/bin/activate && pytest -v -s --html=reports/Test_Execution_Report.html'
            }
        }
    }

    post {
        always {
            // Archive test reports
            archiveArtifacts artifacts: 'reports/Test_Execution_Report.html', fingerprint: true
        }
    }
}
